[project]
name = "code-assistant-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.6.3",
    "mem0ai>=0.1.117",
    "openai==1.98.0",
    "openai-agents==0.2.5",
    "tavily-python>=0.7.10",
]
